[package]
name = "tester"
version = "0.1.0"
authors = ["Daniel Lim <orcas@octalorca.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chargen = { version = "0.1.0", path = "../chargen" }
