[package]
name = "vg-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
quick-xml = "0.22.0"
thiserror = "1.0.30"
usvg = "0.19.0"
